title: "The Potato Project"
description: "Arlo's College Search Dashboard"
show_downloads: false
theme: jekyll-theme-slate

exclude: ["LICENSE", "README.md", "shipit", "shipit-rsync", "docs/", "script/", "jekyll-theme-slate.gemspec", "*~"]

